source 'https://github.com/CocoaPods/Specs.git'

target 'ITSegmentedControl', :exclusive => true do
  pod "ITSegmentedControl", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ITSegmentedControl", :path => "../"

  
end
